### PR TITLE
Template generator questionnaire with simple questions

### PR DESCRIPTION
**Pull request by rdgoite**
This an initial implementation of the template generator questionnaire. These only contains simple questions that have fixed/known options for answers.

### CODE REVIEW

**Comment by aaclan-ebi** [comment]
I don't want to impede you but you could reuse or extend the metadata-schema-form component. It might actually save you the work of extracting the data from the form which is still missing in this PR. @MightyAx 's fixing some of the issues he found in that component.

**Comment by MightyAx** [comment]
I'd like to propose we reject this PR in favour of this alternate branch: https://github.com/ebi-ait/ingest-ui/tree/feature/template-questionnaire because:

1. It'll be easier too add the remaining questions that require ontology lookups,
1. The form already outputs the data entered by the user.
1. The form can take data input, so it can be gathered from the project / pre-project information.

**Comment by rolando-ebi** [comment]
For both branches, I think we need a service that converts the questionaire answers into an object that can be serialised and pass to the spreadsheet generator service. The spreadsheet generator service won't be aware of this questionaire

**Comment by MightyAx** [comment]
We agreed on slack to close this PR.

**Pull request closed without merging**
