### PR TITLE
Feature Flagging

### PR DESCRIPTION
**Pull request by rdgoite**
This PR contains changes that enables operations to toggle features on or off in the UI without having to rebuild image for deployment.

See the README for more details.

### CODE REVIEW

**Comment by aaclan-ebi** [comment]
why was this needed?

**Comment by MightyAx** [comment]
Further to Alegria's point. The last time we talked about feature flagging as a team the general sentiment was that while there would be benefits, it would be a big change in our workflow to use effectively.

From our discussions I don't think the rest of the team wants to invest time in changing our development practices in this way.

**Comment by rdgoite** [comment]
This will facilitate releasing UI features quickly through the pipeline. If we don't want to use it, fine, but at least we have the option. Obviously, the hope is that we change the way we do things for the better. 

Note however, that the changes in this PR also includes the mechanism for processing system variables.

**Comment by aaclan-ebi** [comment]
It's not like we don't want to use this. I like it. I would still like this to be merged but I believe we could have planned the work here. The time spent here for this sprint could have been spent on some other tasks to accomplish the goal for this sprint.

**Comment by rdgoite** [comment]
We were blocked on the template generator anyway, and also the task of initially handling form with a dummy generator was also achieved. I'm not sure exactly what between Friday and early Monday afternoon we could have done for the sprint that ends the next day anyway. Also planning work for this without seeing something running would have probably taken more time than I've actually spent on it, with documents, proposals, meetings, etc. and all the resulting back and forth communication. With this PR, we have something to actually talk about and iterate on.

**Comment by aaclan-ebi** [comment]
This is not necessary atm.

**Pull request closed without merging**
